const jaipurJsonData = [
  {
    sno: 1,
    metro_ID: 3,
    station_ID: 1,
    route_ID: 1,
    station_Name: "Badi Chaupar",
    latitude: "26.9239° N",
    longitude: "75.8316° E",

    station_Code: "BACH",
    isJunction: "No",
    route_color: "yellow",
  },
  {
    sno: 2,
    metro_ID: 3,
    station_ID: 2,
    route_ID: 1,
    station_Name: "Chandpole",
    latitude: "26.9243° N",
    longitude: "75.8124° E",
    station_Code: "CHAP",
    isJunction: "No",
    route_color: "yellow",
  },
  {
    sno: 3,
    metro_ID: 3,
    station_ID: 3,
    route_ID: 1,
    station_Name: "Chhoti Chaupar",
    latitude: "26.9247° N",
    longitude: "75.8185° E",
    station_Code: "CHAU",
    isJunction: "No",
    route_color: "yellow",
  },
  {
    sno: 4,
    metro_ID: 3,
    station_ID: 4,
    route_ID: 1,
    station_Name: "Civil Lines",
    latitude: "26.9059° N",
    longitude: "75.7844° E",
    station_Code: "CILI",
    isJunction: "No",
    route_color: "yellow",
  },
  {
    sno: 5,
    metro_ID: 3,
    station_ID: 5,
    route_ID: 1,
    station_Name: "Mansarovar",
    latitude: "26.8505° N",
    longitude: "75.7628° E",
    station_Code: "MANS",
    isJunction: "No",
    route_color: "yellow",
  },
  {
    sno: 6,
    metro_ID: 3,
    station_ID: 6,
    route_ID: 1,
    station_Name: "New Aatish Market",
    latitude: "26.8784° N",
    longitude: "75.7597° E",
    station_Code: "NAMR",
    isJunction: "No",
    route_color: "yellow",
  },
  {
    sno: 7,
    metro_ID: 3,
    station_ID: 7,
    route_ID: 1,
    station_Name: "Railway Station",
    latitude: "26.9196° N",
    longitude: "75.7880° E",
    station_Code: "RAST",
    isJunction: "No",
    route_color: "yellow",
  },
  {
    sno: 8,
    metro_ID: 3,
    station_ID: 8,
    route_ID: 1,
    station_Name: "Ram Nagar",
    latitude: "26.9008° N",
    longitude: "75.7783° E",
    station_Code: "RANR",
    isJunction: "No",
    route_color: "yellow",
  },
  {
    sno: 9,
    metro_ID: 3,
    station_ID: 9,
    route_ID: 1,
    station_Name: "Sindhi Camp",
    latitude: "26.9252° N",
    longitude: "75.8011° E",
    station_Code: "SICA",
    isJunction: "Yes",
    route_color: "yellow",
  },
  {
    sno: 10,
    metro_ID: 3,
    station_ID: 10,
    route_ID: 1,
    station_Name: "Shyam Nagar",
    latitude: "26.8882° N,",
    longitude: "75.7612° E",
    station_Code: "SHNA",
    isJunction: "No",
    route_color: "yellow",
  },
  {
    sno: 11,
    metro_ID: 3,
    station_ID: 11,
    route_ID: 1,
    station_Name: "Vivek Vihar",
    latitude: "26.8886° N",
    longitude: "75.7644° E",
    station_Code: "VIVK",
    isJunction: "No",
    route_color: "yellow",
  },
  {
    sno: 12,
    metro_ID: 3,
    station_ID: 12,
    route_ID: 2,
    station_Name: "Durgapura",
    latitude: "26.8518° N",
    longitude: "75.7862° E",
    station_Code: "DPA",
    isJunction: "No",
    route_color: "red",
  },
  {
    sno: 13,
    metro_ID: 3,
    station_ID: 13,
    route_ID: 2,
    station_Name: "EP Station",
    latitude: "26.922070",
    longitude: "75.778885",
    station_Code: "EPS",
    isJunction: "No",
    route_color: "red",
  },
  {
    sno: 14,
    metro_ID: 3,
    station_ID: 14,
    route_ID: 2,
    station_Name: "Fortis",
    latitude: "26.8462° N",
    longitude: "75.8035° E",
    station_Code: "FTS",
    isJunction: "No",
    route_color: "red",
  },
  {
    sno: 15,
    metro_ID: 3,
    station_ID: 15,
    route_ID: 2,
    station_Name: "WT Park",
    latitude: "26.8530° N",
    longitude: "75.8047° E",
    station_Code: "WTP",
    isJunction: "No",
    route_color: "red",
  },
  {
    sno: 16,
    metro_ID: 3,
    station_ID: 16,
    route_ID: 2,
    station_Name: "Malviya",
    latitude: "26.8549° N",
    longitude: "75.8243° E",
    station_Code: "MLA",
    isJunction: "No",
    route_color: "red",
  },
  {
    sno: 17,
    metro_ID: 3,
    station_ID: 17,
    route_ID: 2,
    station_Name: "Jawahar Kala Kendra",
    latitude: "26.8763° N",
    longitude: "75.8092° E",
    station_Code: "JKK",
    isJunction: "No",
    route_color: "red",
  },
  {
    sno: 18,
    metro_ID: 3,
    station_ID: 18,
    route_ID: 2,
    station_Name: "Bajaj Nagar",
    latitude: "26.8657° N",
    longitude: "75.8013° E",
    station_Code: "BJS",
    isJunction: "No",
    route_color: "red",
  },
  {
    sno: 19,
    metro_ID: 3,
    station_ID: 19,
    route_ID: 2,
    station_Name: "Tonk Pathak",
    latitude: "26.8793° N",
    longitude: "75.7908° E",
    station_Code: "TPS",
    isJunction: "No",
    route_color: "red",
  },
  {
    sno: 20,
    metro_ID: 3,
    station_ID: 20,
    route_ID: 2,
    station_Name: "Gandhi Nagar Mode",
    latitude: "26.8802° N",
    longitude: "75.8060° E",
    station_Code: "GNM",
    isJunction: "No",
    route_color: "red",
  },
  {
    sno: 21,
    metro_ID: 3,
    station_ID: 21,
    route_ID: 2,
    station_Name: "S Manisingh Stadium",
    latitude: "26.8961° N",
    longitude: "75.8045° E",
    station_Code: "SMS",
    isJunction: "No",
    route_color: "red",
  },
  {
    sno: 22,
    metro_ID: 3,
    station_ID: 22,
    route_ID: 2,
    station_Name: "Narayan Singh Circle",
    latitude: "26.8990° N",
    longitude: "75.8118° E",
    station_Code: "NSC",
    isJunction: "No",
    route_color: "red",
  },
  {
    sno: 23,
    metro_ID: 3,
    station_ID: 23,
    route_ID: 2,
    station_Name: "SMS Hospital",
    latitude: "26.9062° N",
    longitude: "75.8163° E",
    station_Code: "SHS",
    isJunction: "No",
    route_color: "red",
  },
  {
    sno: 24,
    metro_ID: 3,
    station_ID: 24,
    route_ID: 2,
    station_Name: "Govt. Hospital",
    latitude: "26.8518° N",
    longitude: "75.7862° E",
    station_Code: "GHS",
    isJunction: "No",
    route_color: "red",
  },
  {
    sno: 25,
    metro_ID: 3,
    station_ID: 25,
    route_ID: 2,
    station_Name: "Ajmeri Gate",
    latitude: "26.8518° N",
    longitude: "75.7862° E",
    station_Code: "AGS",
    isJunction: "No",
    route_color: "red",
  },
  {
    sno: 26,
    metro_ID: 3,
    station_ID: 26,
    route_ID: 2,
    station_Name: "Sindhi camp",
    latitude: "26.8518° N",
    longitude: "75.7862° E",
    station_Code: "SCS",
    isJunction: "Yes",
    route_color: "red",
  },
  {
    sno: 27,
    metro_ID: 3,
    station_ID: 27,
    route_ID: 2,
    station_Name: "Subash Nagar",
    latitude: "26.8518° N",
    longitude: "75.7862° E",
    station_Code: "SNS",
    isJunction: "No",
    route_color: "red",
  },
  {
    sno: 28,
    metro_ID: 3,
    station_ID: 28,
    route_ID: 2,
    station_Name: "Pani Pech",
    latitude: "26.8518° N",
    longitude: "75.7862° E",
    station_Code: "SNS",
    isJunction: "No",
    route_color: "red",
  },
  {
    sno: 29,
    metro_ID: 3,
    station_ID: 29,
    route_ID: 2,
    station_Name: "Ambabadi",
    latitude: "26.8518° N",
    longitude: "75.7862° E",
    station_Code: "ADS",
    isJunction: "No",
    route_color: "red",
  },
  {
    sno: 30,
    metro_ID: 3,
    station_ID: 29,
    route_ID: 3,
    station_Name: "Ambabadi",
    latitude: "26.8518° N",
    longitude: "75.7862° E",
    station_Code: "ADS",
    isJunction: "No",
    route_color: "pink",
  },
  {
    sno: 31,
    metro_ID: 3,
    station_ID: 29,
    route_ID: 3,
    station_Name: "Ambabadi",
    latitude: "26.8518° N",
    longitude: "75.7862° E",
    station_Code: "ADS",
    isJunction: "No",
    route_color: "pink",
  },
  {
    sno: 32,
    metro_ID: 3,
    station_ID: 29,
    route_ID: 3,
    station_Name: "Ambabadi",
    latitude: "26.8518° N",
    longitude: "75.7862° E",
    station_Code: "ADS",
    isJunction: "No",
    route_color: "pink",
  },
  {
    sno: 33,
    metro_ID: 3,
    station_ID: 29,
    route_ID: 3,
    station_Name: "Ambabadi",
    latitude: "26.8518° N",
    longitude: "75.7862° E",
    station_Code: "ADS",
    isJunction: "No",
    route_color: "pink",
  },
  {
    sno: 34,
    metro_ID: 3,
    station_ID: 29,
    route_ID: 3,
    station_Name: "Ambabadi",
    latitude: "26.8518° N",
    longitude: "75.7862° E",
    station_Code: "ADS",
    isJunction: "No",
    route_color: "pink",
  },
  {
    sno: 35,
    metro_ID: 3,
    station_ID: 29,
    route_ID: 3,
    station_Name: "Ambabadi",
    latitude: "26.8518° N",
    longitude: "75.7862° E",
    station_Code: "ADS",
    isJunction: "No",
    route_color: "pink",
  },
  {
    sno: 36,
    metro_ID: 3,
    station_ID: 29,
    route_ID: 3,
    station_Name: "Ambabadi",
    latitude: "26.8518° N",
    longitude: "75.7862° E",
    station_Code: "ADS",
    isJunction: "No",
    route_color: "pink",
  },
  {
    sno: 37,
    metro_ID: 3,
    station_ID: 29,
    route_ID: 3,
    station_Name: "Ambabadi",
    latitude: "26.8518° N",
    longitude: "75.7862° E",
    station_Code: "ADS",
    isJunction: "No",
    route_color: "pink",
  },
  {
    sno: 38,
    metro_ID: 3,
    station_ID: 29,
    route_ID: 3,
    station_Name: "Ambabadi",
    latitude: "26.8518° N",
    longitude: "75.7862° E",
    station_Code: "ADS",
    isJunction: "No",
    route_color: "pink",
  },
  {
    sno: 39,
    metro_ID: 3,
    station_ID: 29,
    route_ID: 3,
    station_Name: "Ambabadi",
    latitude: "26.8518° N",
    longitude: "75.7862° E",
    station_Code: "ADS",
    isJunction: "No",
    route_color: "pink",
  },
  {
    sno: 40,
    metro_ID: 3,
    station_ID: 29,
    route_ID: 3,
    station_Name: "Ambabadi",
    latitude: "26.8518° N",
    longitude: "75.7862° E",
    station_Code: "ADS",
    isJunction: "No",
    route_color: "pink",
  },
  {
    sno: 41,
    metro_ID: 3,
    station_ID: 29,
    route_ID: 4,
    station_Name: "Ambabadi",
    latitude: "26.8518° N",
    longitude: "75.7862° E",
    station_Code: "ADS",
    isJunction: "No",
    route_color: "green",
  },
  {
    sno: 42,
    metro_ID: 3,
    station_ID: 29,
    route_ID: 4,
    station_Name: "Ambabadi",
    latitude: "26.8518° N",
    longitude: "75.7862° E",
    station_Code: "ADS",
    isJunction: "No",
    route_color: "green",
  },
  {
    sno: 43,
    metro_ID: 3,
    station_ID: 29,
    route_ID: 4,
    station_Name: "Ambabadi",
    latitude: "26.8518° N",
    longitude: "75.7862° E",
    station_Code: "ADS",
    isJunction: "No",
    route_color: "green",
  },
  {
    sno: 44,
    metro_ID: 3,
    station_ID: 29,
    route_ID: 4,
    station_Name: "Ambabadi",
    latitude: "26.8518° N",
    longitude: "75.7862° E",
    station_Code: "ADS",
    isJunction: "No",
    route_color: "green",
  },
  {
    sno: 45,
    metro_ID: 3,
    station_ID: 29,
    route_ID: 4,
    station_Name: "Ambabadi",
    latitude: "26.8518° N",
    longitude: "75.7862° E",
    station_Code: "ADS",
    isJunction: "No",
    route_color: "green",
  },
  {
    sno: 46,
    metro_ID: 3,
    station_ID: 29,
    route_ID: 4,
    station_Name: "Ambabadi",
    latitude: "26.8518° N",
    longitude: "75.7862° E",
    station_Code: "ADS",
    isJunction: "No",
    route_color: "green",
  },
  {
    sno: 47,
    metro_ID: 3,
    station_ID: 29,
    route_ID: 4,
    station_Name: "Ambabadi",
    latitude: "26.8518° N",
    longitude: "75.7862° E",
    station_Code: "ADS",
    isJunction: "No",
    route_color: "green",
  },
  {
    sno: 48,
    metro_ID: 3,
    station_ID: 29,
    route_ID: 4,
    station_Name: "Ambabadi",
    latitude: "26.8518° N",
    longitude: "75.7862° E",
    station_Code: "ADS",
    isJunction: "No",
    route_color: "green",
  },
  {
    sno: 49,
    metro_ID: 3,
    station_ID: 29,
    route_ID: 4,
    station_Name: "Ambabadi",
    latitude: "26.8518° N",
    longitude: "75.7862° E",
    station_Code: "ADS",
    isJunction: "No",
    route_color: "green",
  },
  {
    sno: 50,
    metro_ID: 3,
    station_ID: 29,
    route_ID: 4,
    station_Name: "Ambabadi",
    latitude: "26.8518° N",
    longitude: "75.7862° E",
    station_Code: "ADS",
    isJunction: "No",
    route_color: "green",
  },
];

export default jaipurJsonData;
